export const SET_POSTS = 'SET_POSTS';
export const SET_POST_IMG = 'SET_POST_IMG';
export const SET_WATCHED_POST = 'SET_WATCHED_POST';
export const SET_WATCHED_POST_IMG = 'SET_WATCHED_POST_IMG';
export const CLEAR_WATCHED_POST = 'CLEAR_WATCHED_POST';
