export const SET_FOLLOWER_USERS = 'SET_FOLLOWER_USERS';
export const CLEAR_FOLLOWERS = 'CLEAR_FOLLOWERS';
export const SET_FOLLOWING_USERS = 'SET_FOLLOWING_USERS';
export const CLEAR_FOLLOWING = 'CLEAR_FOLLOWING';
export const SET_WATCHED_PEOPLE = 'SET_WATCHED_PEOPLE';
