export const SET_MOVIES = 'SET_MOVIES';
export const SET_WATCHED_MOVIE = 'SET_WATCHED_MOVIE';
export const SET_WATCHED_MOVIE_RATINGS = 'SET_WATCHED_MOVIE_RATINGS';
export const SET_WISHED_MOVIES = 'SET_WISHED_MOVIES';
export const CLEAR_WISHED_MOVIES = 'CLEAR_WISHED_MOVIES';
