export const SET_WATCHED_USER = 'SET_WATCHED_USER';
export const SET_WATCHED_USER_FOLLOWERS = 'SET_WATCHED_USER_FOLLOWERS';
export const CLEAR_WATCHED_USER_FOLLOWERS = 'CLEAR_WATCHED_USER_FOLLOWERS';
export const SET_WATCHED_USER_FOLLOWING = 'SET_WATCHED_USER_FOLLOWING';
export const CLEAR_WATCHED_USER_FOLLOWING = 'CLEAR_WATCHED_USER_FOLLOWING';
